### ISSUE TITLE
-ls doesn't seem to work

### ISSUE THREAD

**Issue by eerie** [maebert/jrnl#328]
I've tried to list journals, but jrnl -ls just outputs "default" although there is at least one journal to list, as jrnl -n 1 correctly shows.
~$ jrnl --version
jrnl version 1.9.8

~$ jrnl -n 1
2015-01-26 20:14 jrnl.
| I'm writing this journal using vim.

~$ jrnl -ls
default

**Comment by kmac** [comment]
I think maybe you are confusing the -ls option - it lists your journal *files* that you have configured, not the journal *entries*.  

When you execute `jrnl -n 1` you're showing the last entry of your default journal file. `jrnl -ls` shows you 'default' because that's the name of your default journal. 

Have a look at the `~/.jrnl_config` file in your home directory if you want to configure more than one journal file. Check out the Advanced Usage section in the docs for more information.

**Comment by eerie** [comment]
Ok thanks.
