### ISSUE TITLE
Multi-authors journal

### ISSUE THREAD

**Issue by Starfight** [maebert/jrnl#557]
I search a solution to write manually short log message for a small team and I found your project very interesting. I know to develop in python but before to implement some features missing for my usage, I want to know if you think it's stupid or not.

1. I want to add an information about author, maybe I can add it on each entry or simply create different files ?
2. I want an option to search on all files, maybe to implement a MultiJournal class ? 

I'm also wondering on implement an web interface to view journals.

**Comment by maebert** [comment]
Hi @Starfight, thanks for your questions!

1. I would recommend using tags for that. You can use custom tag characters so that both eg. `#my_project` and `@author_name` work.
2. Yes, that would work - check out the code in the 2.0 branch though, there should be a much better foundation for that already.

Hope that helps!
